/**
 * Language Context - Çok Dilli Destek
 * TR, EN, RU, AZ
 */
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

// ─── Çeviriler ────────────────────────────────────────────────────────────────
const translations = {
  tr: {
    // Navbar
    home: 'Ana Sayfa',
    categories: 'Kategoriler',
    food: 'Yemek',
    clothing: 'Giyim',
    electronics: 'Elektronik',
    search: 'Ürün, marka veya kategori ara...',
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    profile: 'Profilim',
    orders: 'Siparişlerim',
    favorites: 'Favorilerim',
    cart: 'Sepetim',
    messages: 'Mesajlar',
    notifications: 'Bildirimler',
    settings: 'Ayarlar',
    admin: 'Yönetim Paneli',

    // Hero
    hero_title: 'Her Şey Tek Platformda',
    hero_subtitle: 'Yemek, giyim ve daha fazlası — hepsi PazaRa\'da!',
    hero_cta: 'Alışverişe Başla',
    hero_food_cta: 'Yemek Sipariş Et',

    // Sections
    trending: 'Trend Ürünler',
    featured: 'Öne Çıkanlar',
    new_arrivals: 'Yeni Gelenler',
    best_sellers: 'En Çok Satanlar',
    ai_recommendations: 'AI Önerileri',
    trending_hashtags: 'Trend Hashtagler',
    popular_restaurants: 'Popüler Restoranlar',

    // Product
    add_to_cart: 'Sepete Ekle',
    buy_now: 'Hemen Al',
    add_to_favorites: 'Favorilere Ekle',
    remove_from_favorites: 'Favorilerden Çıkar',
    in_stock: 'Stokta Var',
    out_of_stock: 'Stok Yok',
    free_shipping: 'Ücretsiz Kargo',
    reviews: 'Yorum',
    rating: 'Puan',
    sold: 'Satıldı',
    share: 'Paylaş',
    report: 'Şikayet Et',

    // Cart
    cart_empty: 'Sepetiniz boş',
    cart_empty_desc: 'Alışverişe başlamak için ürün ekleyin',
    checkout: 'Siparişi Tamamla',
    continue_shopping: 'Alışverişe Devam Et',
    total: 'Toplam',
    subtotal: 'Ara Toplam',
    delivery_fee: 'Kargo Ücreti',
    discount: 'İndirim',
    coupon: 'Kupon Kodu',
    apply: 'Uygula',

    // Auth
    email: 'E-posta',
    password: 'Şifre',
    confirm_password: 'Şifre Tekrar',
    full_name: 'Ad Soyad',
    username: 'Kullanıcı Adı',
    phone: 'Telefon',
    remember_me: 'Beni Hatırla',
    forgot_password: 'Şifremi Unuttum',
    no_account: 'Hesabınız yok mu?',
    have_account: 'Zaten hesabınız var mı?',
    sign_up: 'Kayıt Ol',
    sign_in: 'Giriş Yap',
    or: 'veya',

    // Orders
    order_status: 'Sipariş Durumu',
    pending: 'Beklemede',
    confirmed: 'Onaylandı',
    preparing: 'Hazırlanıyor',
    shipping: 'Kargoda',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal Edildi',
    order_number: 'Sipariş No',
    order_date: 'Sipariş Tarihi',
    track_order: 'Siparişi Takip Et',
    cancel_order: 'Siparişi İptal Et',

    // AI
    ai_title: 'AI Asistanınız',
    ai_subtitle: 'Size özel ürün önerileri',
    ai_chat: 'AI ile Sohbet',
    ai_typing: 'Yazıyor...',
    ai_placeholder: 'Bir şeyler sorun...',
    ai_send: 'Gönder',

    // General
    loading: 'Yükleniyor...',
    error: 'Hata oluştu',
    retry: 'Tekrar Dene',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    view_all: 'Tümünü Gör',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    close: 'Kapat',
    confirm: 'Onayla',
    yes: 'Evet',
    no: 'Hayır',
    currency: '₺',
    language: 'Dil',
  },

  en: {
    home: 'Home',
    categories: 'Categories',
    food: 'Food',
    clothing: 'Clothing',
    electronics: 'Electronics',
    search: 'Search products, brands or categories...',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    profile: 'My Profile',
    orders: 'My Orders',
    favorites: 'Favorites',
    cart: 'Cart',
    messages: 'Messages',
    notifications: 'Notifications',
    settings: 'Settings',
    admin: 'Admin Panel',
    hero_title: 'Everything in One Platform',
    hero_subtitle: 'Food, clothing and more — all on PazaRa!',
    hero_cta: 'Start Shopping',
    hero_food_cta: 'Order Food',
    trending: 'Trending Products',
    featured: 'Featured',
    new_arrivals: 'New Arrivals',
    best_sellers: 'Best Sellers',
    ai_recommendations: 'AI Recommendations',
    trending_hashtags: 'Trending Hashtags',
    popular_restaurants: 'Popular Restaurants',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    add_to_favorites: 'Add to Favorites',
    remove_from_favorites: 'Remove from Favorites',
    in_stock: 'In Stock',
    out_of_stock: 'Out of Stock',
    free_shipping: 'Free Shipping',
    reviews: 'Reviews',
    rating: 'Rating',
    sold: 'Sold',
    share: 'Share',
    report: 'Report',
    cart_empty: 'Your cart is empty',
    cart_empty_desc: 'Add products to start shopping',
    checkout: 'Checkout',
    continue_shopping: 'Continue Shopping',
    total: 'Total',
    subtotal: 'Subtotal',
    delivery_fee: 'Delivery Fee',
    discount: 'Discount',
    coupon: 'Coupon Code',
    apply: 'Apply',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    full_name: 'Full Name',
    username: 'Username',
    phone: 'Phone',
    remember_me: 'Remember Me',
    forgot_password: 'Forgot Password',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    sign_up: 'Sign Up',
    sign_in: 'Sign In',
    or: 'or',
    order_status: 'Order Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    preparing: 'Preparing',
    shipping: 'Shipping',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    order_number: 'Order No',
    order_date: 'Order Date',
    track_order: 'Track Order',
    cancel_order: 'Cancel Order',
    ai_title: 'Your AI Assistant',
    ai_subtitle: 'Personalized product recommendations',
    ai_chat: 'Chat with AI',
    ai_typing: 'Typing...',
    ai_placeholder: 'Ask something...',
    ai_send: 'Send',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view_all: 'View All',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    currency: '₺',
    language: 'Language',
  },

  ru: {
    home: 'Главная',
    categories: 'Категории',
    food: 'Еда',
    clothing: 'Одежда',
    electronics: 'Электроника',
    search: 'Поиск товаров, брендов или категорий...',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    profile: 'Мой профиль',
    orders: 'Мои заказы',
    favorites: 'Избранное',
    cart: 'Корзина',
    messages: 'Сообщения',
    notifications: 'Уведомления',
    settings: 'Настройки',
    admin: 'Панель администратора',
    hero_title: 'Всё на одной платформе',
    hero_subtitle: 'Еда, одежда и многое другое — всё на PazaRa!',
    hero_cta: 'Начать покупки',
    hero_food_cta: 'Заказать еду',
    trending: 'Популярные товары',
    featured: 'Рекомендуемые',
    new_arrivals: 'Новинки',
    best_sellers: 'Бестселлеры',
    ai_recommendations: 'Рекомендации ИИ',
    trending_hashtags: 'Популярные хэштеги',
    popular_restaurants: 'Популярные рестораны',
    add_to_cart: 'В корзину',
    buy_now: 'Купить сейчас',
    add_to_favorites: 'В избранное',
    remove_from_favorites: 'Из избранного',
    in_stock: 'В наличии',
    out_of_stock: 'Нет в наличии',
    free_shipping: 'Бесплатная доставка',
    reviews: 'Отзывы',
    rating: 'Рейтинг',
    sold: 'Продано',
    share: 'Поделиться',
    report: 'Пожаловаться',
    cart_empty: 'Ваша корзина пуста',
    cart_empty_desc: 'Добавьте товары для начала покупок',
    checkout: 'Оформить заказ',
    continue_shopping: 'Продолжить покупки',
    total: 'Итого',
    subtotal: 'Подытог',
    delivery_fee: 'Стоимость доставки',
    discount: 'Скидка',
    coupon: 'Промокод',
    apply: 'Применить',
    email: 'Эл. почта',
    password: 'Пароль',
    confirm_password: 'Подтвердить пароль',
    full_name: 'Полное имя',
    username: 'Имя пользователя',
    phone: 'Телефон',
    remember_me: 'Запомнить меня',
    forgot_password: 'Забыли пароль',
    no_account: 'Нет аккаунта?',
    have_account: 'Уже есть аккаунт?',
    sign_up: 'Зарегистрироваться',
    sign_in: 'Войти',
    or: 'или',
    order_status: 'Статус заказа',
    pending: 'Ожидание',
    confirmed: 'Подтверждён',
    preparing: 'Готовится',
    shipping: 'Доставляется',
    delivered: 'Доставлен',
    cancelled: 'Отменён',
    order_number: 'Номер заказа',
    order_date: 'Дата заказа',
    track_order: 'Отследить заказ',
    cancel_order: 'Отменить заказ',
    ai_title: 'Ваш ИИ-ассистент',
    ai_subtitle: 'Персональные рекомендации товаров',
    ai_chat: 'Чат с ИИ',
    ai_typing: 'Печатает...',
    ai_placeholder: 'Задайте вопрос...',
    ai_send: 'Отправить',
    loading: 'Загрузка...',
    error: 'Произошла ошибка',
    retry: 'Повторить',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    view_all: 'Смотреть все',
    back: 'Назад',
    next: 'Далее',
    previous: 'Предыдущий',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    yes: 'Да',
    no: 'Нет',
    currency: '₺',
    language: 'Язык',
  },

  az: {
    home: 'Ana Səhifə',
    categories: 'Kateqoriyalar',
    food: 'Yemək',
    clothing: 'Geyim',
    electronics: 'Elektronika',
    search: 'Məhsul, marka və ya kateqoriya axtar...',
    login: 'Daxil ol',
    register: 'Qeydiyyat',
    logout: 'Çıxış',
    profile: 'Profilim',
    orders: 'Sifarişlərim',
    favorites: 'Sevimlilər',
    cart: 'Səbət',
    messages: 'Mesajlar',
    notifications: 'Bildirişlər',
    settings: 'Parametrlər',
    admin: 'İdarəetmə Paneli',
    hero_title: 'Hər Şey Bir Platformda',
    hero_subtitle: 'Yemək, geyim və daha çox — hamısı PazaRa\'da!',
    hero_cta: 'Alış-verişə Başla',
    hero_food_cta: 'Yemək Sifariş Et',
    trending: 'Trend Məhsullar',
    featured: 'Seçilmişlər',
    new_arrivals: 'Yeni Gələnlər',
    best_sellers: 'Ən Çox Satılanlar',
    ai_recommendations: 'AI Tövsiyələri',
    trending_hashtags: 'Trend Hashtaglər',
    popular_restaurants: 'Populyar Restoranlar',
    add_to_cart: 'Səbətə Əlavə Et',
    buy_now: 'İndi Al',
    add_to_favorites: 'Sevimlilərə Əlavə Et',
    remove_from_favorites: 'Sevimlilərdən Çıxar',
    in_stock: 'Stokda Var',
    out_of_stock: 'Stok Yoxdur',
    free_shipping: 'Pulsuz Çatdırılma',
    reviews: 'Rəylər',
    rating: 'Reytinq',
    sold: 'Satıldı',
    share: 'Paylaş',
    report: 'Şikayət Et',
    cart_empty: 'Səbətiniz boşdur',
    cart_empty_desc: 'Alış-verişə başlamaq üçün məhsul əlavə edin',
    checkout: 'Sifarişi Tamamla',
    continue_shopping: 'Alış-verişə Davam Et',
    total: 'Cəmi',
    subtotal: 'Ara Cəm',
    delivery_fee: 'Çatdırılma Haqqı',
    discount: 'Endirim',
    coupon: 'Kupon Kodu',
    apply: 'Tətbiq Et',
    email: 'E-poçt',
    password: 'Şifrə',
    confirm_password: 'Şifrəni Təsdiqlə',
    full_name: 'Ad Soyad',
    username: 'İstifadəçi Adı',
    phone: 'Telefon',
    remember_me: 'Məni Xatırla',
    forgot_password: 'Şifrəmi Unutdum',
    no_account: 'Hesabınız yoxdur?',
    have_account: 'Artıq hesabınız var?',
    sign_up: 'Qeydiyyatdan Keç',
    sign_in: 'Daxil Ol',
    or: 'və ya',
    order_status: 'Sifariş Statusu',
    pending: 'Gözləmədə',
    confirmed: 'Təsdiqləndi',
    preparing: 'Hazırlanır',
    shipping: 'Çatdırılır',
    delivered: 'Çatdırıldı',
    cancelled: 'Ləğv Edildi',
    order_number: 'Sifariş No',
    order_date: 'Sifariş Tarixi',
    track_order: 'Sifarişi İzlə',
    cancel_order: 'Sifarişi Ləğv Et',
    ai_title: 'AI Köməkçiniz',
    ai_subtitle: 'Sizə xüsusi məhsul tövsiyələri',
    ai_chat: 'AI ilə Söhbət',
    ai_typing: 'Yazır...',
    ai_placeholder: 'Bir şey soruşun...',
    ai_send: 'Göndər',
    loading: 'Yüklənir...',
    error: 'Xəta baş verdi',
    retry: 'Yenidən Cəhd Et',
    save: 'Saxla',
    cancel: 'Ləğv Et',
    delete: 'Sil',
    edit: 'Redaktə Et',
    view_all: 'Hamısını Gör',
    back: 'Geri',
    next: 'İrəli',
    previous: 'Əvvəlki',
    close: 'Bağla',
    confirm: 'Təsdiqlə',
    yes: 'Bəli',
    no: 'Xeyr',
    currency: '₺',
    language: 'Dil',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('pazara_lang') || 'tr'
  );

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('pazara_lang', lang);
    document.documentElement.lang = lang;
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['tr']?.[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export default LanguageContext;
